apiVersion: v1
kind: Service
metadata:
  name: back-app-service
spec:
  selector:
    app: back-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer # Expose internally within the cluster
