apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 3 # Number of desired replicas
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: fist-app
        image: arshadghazi/myrepo:44