version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Expose the backend port (if needed)
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://database:27017/my_db # Replace 'my_db' with your actual database name
    depends_on:
      -  database
    command: sh -c "sleep 10 && npm start"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # Expose the frontend port (if needed)
    ports:
      - "80:80"
    # Connect frontend to the backend service
    depends_on:
      - backend

  database:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
