apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: asia-east1-docker.pkg.dev/deep-beanbag-392509/t-cr/static-site:latest
    newName: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE
    newTag: $GITHUB_SHA
